### ISSUE TITLE
Duplicate instances? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/saul#357]
When training POS tagger, there is a significant number of warning msgs emitted[ by this line](https://github.com/IllinoisCogComp/saul/blob/master/saul-core/src/main/scala/edu/illinois/cs/cogcomp/saul/datamodel/node/Node.scala#L128), which indicates that there is repetitions in the instances. This doesn't look right ....

**Comment by bhargav** [comment]
Looked at this issue. This happens because of the `sensors` for the context windows constituents. When we start populating tokens, we recursively go through each edge and try to add the tokens at the edge. That way, we end up populating all tokens for a sentence while processing the first token of the sentence. Rest of the tokens give the warning message.

**Comment by danyaljj** [comment]
Makes sense. It's good to know. Thanks
